version: "2"
   
services:
  db:
    image: mysql:5.7
    container_name: my_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ADmin@123Aa
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: Wp123@123a
   
  web:
    depends_on:
      - db
    image: wordpress:latest
    container_name: my_web
    volumes:
      - code_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Wp123@123a
      WORDPRESS_DB_NAME: wp_db
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data: {}
  code_data: {}
